name: Create Category Pages

on:
  push:
    branches:
      - main  # 또는 여러분의 기본 브랜치 이름
    paths:
      - '_posts/**'

jobs:
  create-category-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: | 
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create category pages
        run: |
          # 카테고리 디렉토리 생성
          mkdir -p category

          # _posts 디렉토리의 모든 마크다운 파일 처리
          for file in _posts/*.md; do
            # 파일에서 카테고리 추출
            categories=$(sed -n '/^categories:/,/^[^ ]/p' "$file" | grep -v '^categories:' | sed 's/^- //' | tr -d '[]"' | tr ',' '\n')
            
            # 각 카테고리에 대해 처리
            echo "$categories" | while read -r category; do
              if [ ! -z "$category" ]; then
                # 카테고리 페이지 파일 경로
                category_file="categories/${category}.html"
                
                # 카테고리 페이지가 없으면 생성
                if [ ! -f "$category_file" ]; then
                  echo "---" > "$category_file"
                  echo "layout: category" >> "$category_file"
                  echo "title: Category - $category" >> "$category_file"
                  echo "category: $category" >> "$category_file"
                  echo "---" >> "$category_file"
                  echo "<h2>Posts in category '$category'</h2>" >> "$category_file"
                  echo "{% for post in site.categories['$category'] %}" >> "$category_file"
                  echo "  <li><a href="{{ post.url }}">{{ post.title }}</a></li>" >> "$category_file"
                  echo "{% endfor %}" >> "$category_file"
                  
                  echo "Created category page for $category"
                fi
              fi
            done
          done

      - name: Commit changes
        run: |
          git add categories/
          git commit -m "Automatically create category pages"

      - name: Push changes
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/mamananama/mamananama.github.io.git
          git push origin main